name: LootPlugin
version: 1.1
main: com.example.lootplugin.LootPlugin
api-version: "1.16"
author: yitian
description: 一个功能丰富的搜刮方块插件，支持进度条交互和共享容器机制
website: https://github.com/yitian77/LootPlugin
commands:
  addlootblock:
    description: 添加一个新的搜刮方块
    usage: /addlootblock
    permission: lootplugin.addlootblock
    permission-message: "§c你没有权限添加搜刮方块。"

  addlootitem:
    description: 向搜刮方块添加一个物品
    usage: /addlootitem <数量> <概率>
    permission: lootplugin.addlootitem
    permission-message: "§c你没有权限向搜刮方块添加物品。"

  setprogresstime:
    description: 设置搜刮方块的进度条时间
    usage: /setprogresstime <秒>
    permission: lootplugin.setprogresstime
    permission-message: "§c你没有权限设置进度条时间。"

  setrefreshtime:
    description: 设置搜刮方块的刷新时间
    usage: /setrefreshtime <秒>
    permission: lootplugin.setrefreshtime
    permission-message: "§c你没有权限设置刷新时间。"

  setsounds:
    description: 设置搜刮方块的音效
    usage: /setsounds <start|end|loading|container_open|container_close> <sound>
    permission: lootplugin.setsounds
    permission-message: "§c你没有权限设置音效。"

  reloadlootplugin:
    description: 重载插件配置
    usage: /reloadlootplugin
    permission: lootplugin.reloadlootplugin
    permission-message: "§c你没有权限重载插件配置。"

permissions:
  lootplugin.addlootblock:
    description: 允许玩家添加搜刮方块
    default: op

  lootplugin.addlootitem:
    description: 允许玩家向搜刮方块添加物品
    default: op

  lootplugin.setprogresstime:
    description: 允许玩家设置搜刮方块的进度条时间
    default: op

  lootplugin.setrefreshtime:
    description: 允许玩家设置搜刮方块的刷新时间
    default: op

  lootplugin.setsounds:
    description: 允许玩家设置搜刮方块的音效
    default: op

  lootplugin.reloadlootplugin:
    description: 允许玩家重载插件配置
    default: op

  lootplugin.use:
    description: 允许玩家使用搜刮方块
    default: true